# spinalcord
# https://github.com/spinalcord/animation-tree-tree-godot
# 
# This file is part of animation-tree-tree-godot.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public.
#
# NOTE: The output generated by this addon is not affected by this license.

class_name MetadataUtils
static func create_node_metadata(path: String, node_type: String, node_name: String, has_children: bool) -> Dictionary:
	return {
		"path": path,
		"node_type": node_type,
		"node_name": node_name,
		"has_children": has_children
	}

static func get_path_from_metadata(metadata) -> String:
	if metadata is Dictionary:
		return metadata.get("path", "")
	else:
		return str(metadata) if metadata != null else ""
