# spinalcord
# https://github.com/spinalcord/animation-tree-tree-godot
# 
# This file is part of animation-tree-tree-godot.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public.
#
# NOTE: The output generated by this addon is not affected by this license.

class_name PathUtils
static func build_child_path(parent_path: String, child_name: String) -> String:
	return "%s/%s" % [parent_path, child_name] if not parent_path.is_empty() else child_name
