# spinalcord
# https://github.com/spinalcord/animation-tree-tree-godot
# 
# This file is part of animation-tree-tree-godot.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public.
#
# NOTE: The output generated by this addon is not affected by this license.

class_name SelectionUtils
static func get_selected_items(tree_view: Tree) -> Array[TreeItem]:
	var selected_items: Array[TreeItem] = []
	var root_item: TreeItem = tree_view.get_root()
	if root_item:
		_collect_selected_items(root_item, selected_items)
	return selected_items

static func _collect_selected_items(item: TreeItem, selected_items: Array[TreeItem]) -> void:
	if item.is_selected(0):
		selected_items.append(item)
	
	var child: TreeItem = item.get_first_child()
	while child:
		_collect_selected_items(child, selected_items)
		child = child.get_next()
