# spinalcord
# https://github.com/spinalcord/animation-tree-tree-godot
# 
# This file is part of animation-tree-tree-godot.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public.
#
# NOTE: The output generated by this addon is not affected by this license.

class_name TreeUtils
static func process_tree_children(item: TreeItem, callback: Callable) -> void:
	var child: TreeItem = item.get_first_child()
	while child:
		callback.call(child)
		child = child.get_next()

static func search_tree_children(item: TreeItem, callback: Callable) -> bool:
	var child: TreeItem = item.get_first_child()
	while child:
		if callback.call(child):
			return true
		child = child.get_next()
	return false
