# spinalcord
# https://github.com/spinalcord/animation-tree-tree-godot
# 
# This file is part of animation-tree-tree-godot.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public.
#
# NOTE: The output generated by this addon is not affected by this license.

# SampleTools.gd
class_name FSMExpertTools
extends ConAITool

## You will likely use this function if USER wants to change something
## You can call this function to get the structure of your chosen target_paths
## IF you choose an empty string as target_path you get the Root structure.
## structure.
## [param target_paths]: target paths e.g. ["", "StateA/StateB"] returns structure of Root and structure of StateB
func tool_get_blueprint(target_paths: Array) -> Array[String]:
	var export_manager: ExportManager = ExportManager.new()
	var return_array: Array[String] = []
	for target_path in target_paths:
		var yaml: String = export_manager.export_tree_as_yaml(_animation_tree, [target_path])
		return_array.append(yaml)
		TreeDebug.msg(yaml)
	return return_array

## Deletes transitions from state machines.
## [param target_paths]: Paths to state machines (e.g. ["PlayerAnimationController/GroundState"])
## [param transitions]: Array of transitions [{"from": "state1", "to": "state2"}]
func tool_delete_transitions(target_paths: Array, transitions: Array) -> bool:
	print(target_paths)
	print(transitions)
	var tree_builder: AnimationTreeBuilder = AnimationTreeBuilder.new(_animation_tree)
	var all_success: bool = true
	
	for target_path in target_paths:
		var success: bool = tree_builder.delete_transitions(target_path, transitions)
		if success:
			TreeDebug.msg("Successfully deleted %d transition(s) from %s" % [transitions.size(), target_path])
		else:
			TreeDebug.msg("Failed to delete transitions from %s" % target_path)
			all_success = false
	return all_success
