# spinalcord
# https://github.com/spinalcord/animation-tree-tree-godot
# 
# This file is part of animation-tree-tree-godot.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public.
#
# NOTE: The output generated by this addon is not affected by this license.

# SampleTools.gd
class_name SampleTools
extends ConAITool

## Just a tool to Test tool calling.
## [param test]: param1
## [param test2]: param2
func tool_test(test: String, test2: String = "abc") -> String:
	print("Tool ABC called with: ", test, ", ", test2)
	return "ABC tool result: " + test + " + " + test2
