# spinalcord
# https://github.com/spinalcord/animation-tree-tree-godot
# 
# This file is part of animation-tree-tree-godot.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public.
#
# NOTE: The output generated by this addon is not affected by this license.

class_name ScriptExpertTools
extends ConAITool
# this is a tool class. An agent can use tool to enhance
# your output tools begin with tool prefix. 

## This function returns the Input map.
func tool_get_input_map() -> String:
	return ",".join(InputMap.get_actions())

## Returns Godots current scripting guidline.
func tool_get_godot_scripting_guidline() -> String:
	var file = FileAccess.open(AnimationTreeTree.plugin_path + "ai/guidline/scripting.txt", FileAccess.READ)
	
	# Check if file was opened successfully
	if file == null:
		print("Error opening guidline: ", FileAccess.get_open_error())
		return ""
	
	# Read the entire file content
	var content = file.get_as_text()
	
	# Close the file
	file.close()
	return content
