# spinalcord
# https://github.com/spinalcord/animation-tree-tree-godot
# 
# This file is part of animation-tree-tree-godot.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public.
#
# NOTE: The output generated by this addon is not affected by this license.

class_name Agent
extends Node

var system_prompt: String = "You are an expert in ..."
var con_ai: ConAI
var tools: ConAITool

func _init(con_ai_ref: ConAI = null) -> void:
	if con_ai_ref != null:
		con_ai = con_ai_ref
