# spinalcord
# https://github.com/spinalcord/animation-tree-tree-godot
# 
# This file is part of animation-tree-tree-godot.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public.
#
# NOTE: The output generated by this addon is not affected by this license.

class_name Conversation
var temp_name: String
var chain: Array = []
var timestamp_started: float
var timestamp_last: float

func _init():
	timestamp_started = Time.get_unix_time_from_system()
	timestamp_last = timestamp_started

## Return time in hours: Conversation ended an now
## Helpfull if you meet a Character ingame like 10 Minutes ago.
func time_delta() -> float:
	var now = Time.get_unix_time_from_system()
	var seconds_elapsed = now - timestamp_last
	var hours_elapsed = seconds_elapsed / 3600.0
	return round(hours_elapsed * 10.0) / 10.0  

func add_message(content: String, role: String):
	chain.append({"role": role, "content": content})
	timestamp_last = Time.get_unix_time_from_system()

## Returns the content of the last message with the specified role
## Returns empty string if no message with that role is found
func get_last_message(role_string) -> String:
	
	# Iterate backwards through the conversation chain
	for i in range(self.chain.size() - 1, -1, -1):
		var message = self.chain[i]
		if message.get("role", "") == role_string:
			return message.get("content", "")
	
	return ""
	
func debug_timestamps():
	var now = Time.get_unix_time_from_system()
	TreeDebug.msg("Current time: " + str(now))
	TreeDebug.msg("Started time: " + str(timestamp_started) )
	TreeDebug.msg("Last message time: " + str(timestamp_last))
	TreeDebug.msg("Time since start (hours): " + str(time_delta()))
