# spinalcord
# https://github.com/spinalcord/animation-tree-tree-godot
# 
# This file is part of animation-tree-tree-godot.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public.
#
# NOTE: The output generated by this addon is not affected by this license.

class_name ConfigField
extends RefCounted

var key: String
var label_text: String
var description: String
var tab_name: String
var field_type: String
var default_value

func _init(p_key: String, p_label: String, p_description: String, p_tab: String, p_type: String, p_default):
	key = p_key
	label_text = p_label
	description = p_description
	tab_name = p_tab
	field_type = p_type
	default_value = p_default
