# spinalcord
# https://github.com/spinalcord/animation-tree-tree-godot
# 
# This file is part of animation-tree-tree-godot.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public.
#
# NOTE: The output generated by this addon is not affected by this license.

class_name Expert # In future this will be an abstract class, keep this to support <4.5
var name: String
var manager: AIManager

func get_config_fields() -> Array[ConfigField]:
	return []

func get_system_prompt() -> String:
	return ""

func process(con_ai: ConAI, system_prompt: String, user_input: String) -> void:
	pass
