# spinalcord
# https://github.com/spinalcord/animation-tree-tree-godot
# 
# This file is part of animation-tree-tree-godot.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public.
#
# NOTE: The output generated by this addon is not affected by this license.

# AIManager handles AI-related operations and expert interactions
class_name FSMExpert extends Expert
func _init(ai_manager: AIManager) -> void:
	name = AIManager.FSM_EXPERT
	manager = ai_manager

func get_config_fields() -> Array[ConfigField]:
	var fields: Array[ConfigField] = []
	
	fields.append(ConfigField.new(
		"node_type", 
		"Allowed Node Types", 
		"Select which node types should the expert included/excluded", 
		"State Machine Expert", 
		"decision", 
		{
			"StateMachine": true,
			"BlendTree": true,
			"Animation": true,
			"Blend2": true,
			"Blend3": true,
			"BlendSpace1D": true,
			"BlendSpace2D": true,
			"TimeScale": true,
			"TimeSeek": true,
			"Transition": true
		}
	))
	
	fields.append(ConfigField.new(
		"include_excerpt", 
		"Include Expression Excerpt", 
		"Includes an excerpt (Only booleans) of your \"Advance Expression Base Node\" attached script assigned to your AnimationTree.", 
		"State Machine Expert", 
		"bool", 
		true
	))
	
	return fields

func get_system_prompt() -> String:
	return "fsm_expert.txt"

func process(con_ai: ConAI, system_prompt: String, user_input: String) -> void:
	var fsm_agent: Agent = Agent.new()
	fsm_agent.system_prompt = system_prompt
	
	var temp_conversation: Conversation = Conversation.new()
	var sample_tools = SampleTools.new()
	
	await con_ai.answer(fsm_agent, temp_conversation, sample_tools, user_input)
	var llm_result = temp_conversation.get_last_message("assistant")
	var all_produced_yaml: Array = manager.extract_block_from_markdown(llm_result, "yaml")
	
	
	if all_produced_yaml.size() > 0:
		var first_yaml: String = all_produced_yaml[0]
		var builder: AnimationTreeScriptBuilder = AnimationTreeScriptBuilder.new()
		print(first_yaml)
		
		builder.build_from_script(manager._animation_tree, first_yaml)
		manager._refresh_callback.call()
		EditorInterface.mark_scene_as_unsaved()
